### ISSUE TITLE
How are gas fees calculated?

### ISSUE THREAD

**Issue by 0xSulpiride** [Encode-Club-Solidity-Foundations/Lesson-01#12]

**Comment by MatheusDaros** [comment]
Hello @marie-fourier 
Gas fees are calculated multiplying the gas cost of a transaction (that depends only on the OPCODES being executed there) and the gas price you select (that fluctuates according to the network usage conditions).
You could find an overall explanation on this subject on the pre-work link [here](https://github.com/ethereumbook/ethereumbook/blob/develop/01what-is.asciidoc) and a more detailed explanation on the solidity docs [here](https://docs.soliditylang.org/en/v0.8.17/introduction-to-smart-contracts.html?#gas)
