### ISSUE TITLE
Storage handling

### ISSUE THREAD

**Issue by nikosdk** [Encode-Club-Solidity-Foundations/Lesson-01#27]
Hello, how do we handle where we store data ? For example we are instructed not to store calculations etc. inside the contracts. How is that achieved?

**Comment by MatheusDaros** [comment]
Hello @nikosdk 
Thanks for the question.
We're going to see exactly this on [Lesson 3](https://github.com/Encode-Club-Solidity-Foundations/Lesson-03#function-definition)

**Comment by nikosdk** [comment]
Looking forward to it Matheus, thanks for your time.
