### ISSUE TITLE
Smart Contract Design Best Practice. 

### ISSUE THREAD

**Issue by UsuaOSilver** [Encode-Club-Solidity-Foundations/Lesson-01#30]
Is there a checklist of the things that should be considered such as gas optimization, memory used,... when start writing smart contracts?

**Comment by MatheusDaros** [comment]
Hello @UsuaOSilver 
There is not something like a checklist, but you should indeed consider all those topics mentioned, but also security, architecture, usability, maintainability, readability, and much more

**Comment by UsuaOSilver** [comment]
Good to know that. Thank you!
