### ISSUE TITLE
What is constructor?

### ISSUE THREAD

**Issue by zklim** [Encode-Club-Solidity-Foundations/Lesson-01#8]

**Comment by MatheusDaros** [comment]
Constructor functions are only executed once when the contract is first deployed. Like constructor in many class-based programming languages, these functions often initialize state variables to their specified values.
Read more about it in the docs at [Constructor definition](https://docs.soliditylang.org/en/v0.8.17/contracts.html#constructors) and in the [Contract creation](https://docs.soliditylang.org/en/v0.8.17/contracts.html#creating-contracts).
